# Generated by Django 2.1.3 on 2019-07-11 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('gender', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=45)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
                ('street_name', models.CharField(max_length=55)),
                ('town', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(default='Nigeria', max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
